# Generated by Django 4.1.2 on 2022-10-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True),
        ),
    ]
