# Generated by Django 4.1.2 on 2022-11-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0003_project_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linku',
            field=models.TextField(blank=True),
        ),
    ]
