# Generated by Django 4.1.2 on 2022-11-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
